name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: List @repo/ui build outputs
        run: |
          ls -lR node_modules/@repo/ui/dist || echo 'dist não encontrado'
          ls -lR packages/ui/dist || echo 'dist local não encontrado'
      - name: Coverage
        run: pnpm test:coverage || echo 'No coverage script'
